import jwt

token = "eyJhbGciOiJFUzI1NiIsImtpZCI6Ijc3MTdjOWE1LWVhMmEtNGYxOC1iYWM2LTE0ZDhkYWJiMWY3MyIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJodHRwczovL3BjaG9lbHNmZ3pvcmNiaWRoYnRrLnN1cGFiYXNlLmNvL2F1dGgvdjEiLCJzdWIiOiIwMDlhOTI1NS0xODQxLTQ5NTAtOTNhNC1iMzQ0OTNkOGU4ZTUiLCJhdWQiOiJhdXRoZW50aWNhdGVkIiwiZXhwIjoxNzgyOTIzNzk0LCJpYXQiOjE3ODI5MjAxOTQsImVtYWlsIjoiYXBpLTE3ODI5MjAxODcxMDlAZXhhbXBsZS5jb20iLCJwaG9uZSI6IiIsImFwcF9tZXRhZGF0YSI6eyJwcm92aWRlciI6ImVtYWlsIiwicHJvdmlkZXJzIjpbImVtYWlsIl19LCJ1c2VyX21ldGFkYXRhIjp7ImVtYWlsX3ZlcmlmaWVkIjp0cnVlLCJmdWxsX25hbWUiOiJBZG1pbiBDcmVhdGVkIFRlc3QgVXNlciJ9LCJyb2xlIjoiYXV0aGVudGljYXRlZCIsImFhbCI6ImFhbDEiLCJhbXIiOlt7Im1ldGhvZCI6InBhc3N3b3JkIiwidGltZXN0YW1wIjoxNzgyOTIwMTk0fV0sInNlc3Npb25faWQiOiJkMDljNzBmYy01ZGVkLTQ1ZmEtYWU5My01YmEyMDg4NTM3ZTkiLCJpc19hbm9ueW1vdXMiOmZhbHNlfQ.fTGrxwCMtODbYvDIITHZJzIprKAtTmwWX1mwqRz4-Ryq5TlFjkjplrFNQ9e6hZCgtmtGYBAMu7nNdLLoBNcAUQ"

jwks_client = jwt.PyJWKClient("https://pchoelsfgzorcbidhbtk.supabase.co/auth/v1/.well-known/jwks.json")
signing_key = jwks_client.get_signing_key_from_jwt(token)
try:
    payload = jwt.decode(token, signing_key.key, algorithms=["ES256", "RS256", "HS256"], audience="authenticated")
    print(payload)
except Exception as e:
    print("FAILED:", e)
