"""Sprint 2 schema

Revision ID: 2234be0f5041
Revises: 06acc7453df8
Create Date: 2026-07-01 16:31:04.410796

"""
from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2234be0f5041'
down_revision: str | Sequence[str] | None = '06acc7453df8'
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('permissions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('permission', sa.String(length=255), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('permission')
    )
    op.create_table('roles',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.create_table('audit_logs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('actor_id', sa.UUID(), nullable=False),
    sa.Column('action', sa.String(length=255), nullable=False),
    sa.Column('resource_type', sa.String(length=255), nullable=False),
    sa.Column('resource_id', sa.UUID(), nullable=False),
    sa.Column('before', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('after', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('ip_address', sa.String(length=45), nullable=True),
    sa.Column('user_agent', sa.String(length=1024), nullable=True),
    sa.Column('request_id', sa.String(length=255), nullable=True),
    sa.Column('correlation_id', sa.String(length=255), nullable=True),
    sa.ForeignKeyConstraint(['actor_id'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_audit_logs_action'), 'audit_logs', ['action'], unique=False)
    op.create_index(op.f('ix_audit_logs_actor_id'), 'audit_logs', ['actor_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_correlation_id'), 'audit_logs', ['correlation_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_organization_id'), 'audit_logs', ['organization_id'], unique=False)
    op.create_index(op.f('ix_audit_logs_resource_id'), 'audit_logs', ['resource_id'], unique=False)
    op.create_table('invitations',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('organization_id', sa.UUID(), nullable=False),
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('status', sa.String(length=50), nullable=False),
    sa.Column('token_hash', sa.String(length=255), nullable=False),
    sa.Column('invited_by', sa.UUID(), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['invited_by'], ['users.id'], ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['organization_id'], ['organizations.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('ix_invitation_email_org_pending', 'invitations', ['email', 'organization_id'], unique=True, postgresql_where="status = 'pending'")
    op.create_index(op.f('ix_invitations_organization_id'), 'invitations', ['organization_id'], unique=False)
    op.create_table('role_permissions',
    sa.Column('role_id', sa.UUID(), nullable=False),
    sa.Column('permission_id', sa.UUID(), nullable=False),
    sa.ForeignKeyConstraint(['permission_id'], ['permissions.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['role_id'], ['roles.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('role_id', 'permission_id')
    )
    op.add_column('memberships', sa.Column('organization_id', sa.UUID(), nullable=False))
    op.add_column('memberships', sa.Column('role_id', sa.UUID(), nullable=False))
    op.add_column('memberships', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('memberships', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    op.drop_index(op.f('ix_memberships_org_id'), table_name='memberships')
    op.create_index(op.f('ix_memberships_organization_id'), 'memberships', ['organization_id'], unique=False)
    op.create_unique_constraint('uq_membership_user_org', 'memberships', ['user_id', 'organization_id'])
    op.drop_constraint(op.f('memberships_org_id_fkey'), 'memberships', type_='foreignkey')
    op.create_foreign_key(None, 'memberships', 'organizations', ['organization_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'memberships', 'roles', ['role_id'], ['id'], ondelete='RESTRICT')
    op.drop_column('memberships', 'role')
    op.drop_column('memberships', 'org_id')
    op.add_column('organizations', sa.Column('logo_url', sa.String(length=1024), nullable=True))
    op.add_column('organizations', sa.Column('plan', sa.String(length=50), nullable=False))
    op.add_column('organizations', sa.Column('status', sa.String(length=50), nullable=False))
    op.add_column('organizations', sa.Column('created_by', sa.UUID(), nullable=False))
    op.add_column('organizations', sa.Column('deleted_at', sa.DateTime(timezone=True), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('organizations', 'deleted_at')
    op.drop_column('organizations', 'created_by')
    op.drop_column('organizations', 'status')
    op.drop_column('organizations', 'plan')
    op.drop_column('organizations', 'logo_url')
    op.add_column('memberships', sa.Column('org_id', sa.UUID(), autoincrement=False, nullable=False))
    op.add_column('memberships', sa.Column('role', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    op.drop_constraint('memberships_role_id_fkey', 'memberships', type_='foreignkey')
    op.drop_constraint('memberships_organization_id_fkey', 'memberships', type_='foreignkey')
    op.create_foreign_key(op.f('memberships_org_id_fkey'), 'memberships', 'organizations', ['org_id'], ['id'], ondelete='CASCADE')
    op.drop_constraint('uq_membership_user_org', 'memberships', type_='unique')
    op.drop_index(op.f('ix_memberships_organization_id'), table_name='memberships')
    op.create_index(op.f('ix_memberships_org_id'), 'memberships', ['org_id'], unique=False)
    op.drop_column('memberships', 'deleted_at')
    op.drop_column('memberships', 'status')
    op.drop_column('memberships', 'role_id')
    op.drop_column('memberships', 'organization_id')
    op.drop_table('role_permissions')
    op.drop_index(op.f('ix_invitations_organization_id'), table_name='invitations')
    op.drop_index('ix_invitation_email_org_pending', table_name='invitations', postgresql_where="status = 'pending'")
    op.drop_table('invitations')
    op.drop_index(op.f('ix_audit_logs_resource_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_organization_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_correlation_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_actor_id'), table_name='audit_logs')
    op.drop_index(op.f('ix_audit_logs_action'), table_name='audit_logs')
    op.drop_table('audit_logs')
    op.drop_table('roles')
    op.drop_table('permissions')
    # ### end Alembic commands ###
